#!/bin/bash
################################################################################
#    HPCC SYSTEMS software Copyright (C) 2012 HPCC Systems.
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
################################################################################

compName=$1
hpcc_setenv=$2
source ${hpcc_setenv}
slavename=thorslave_${compName}

timer=15
isAlive=0
echo "Attempting to kill $slavename with SIGTERM"
killall -SIGTERM $slavename > /dev/null 2>&1
while [[ $isAlive -eq 0 && $timer -gt 0 ]];do
    killall -0 $slavename > /dev/null 2>&1
    isAlive=$?
    [[ $isAlive -eq 0 ]] && sleep 0.5
    ((timer--))
done

if [[ $isAlive -eq 0 ]]; then
    echo "Failed to kill slaves with SIGTERM. Sending SIGKILL"
    killall -SIGKILL $slavename > /dev/null 2>&1
fi

rm -f $PID/${slavename}_*.pid > /dev/null 2>&1

