
if ( NOT PREFIX )
if ( WIN32 )
    set( prog86key "ProgramFiles(x86)" )
    if ("$ENV{${prog86key}}" STREQUAL "")
        set( PREFIX "$ENV{ProgramFiles}" )
    else()
        set( PREFIX "$ENV{${prog86key}}" )
    endif()
    string(REGEX REPLACE "\\\\" "/" PREFIX ${PREFIX})    
else (WIN32)
    set( PREFIX "/opt" )
endif (WIN32)    
endif()

set(EXEC_PREFIX "/var" CACHE STRING "System prefix for runtime files, logging, pid, and lock files")
set(CONF_PREFIX "/etc" CACHE STRING "System prefix for configuration files")
set(HOME_PREFIX "/home" CACHE STRING "System prefix for user home directory")

set(RUNTIME_USER "hpcc" CACHE STRING "Runtime user for hpcc platform")
set(RUNTIME_GROUP "hpcc" CACHE STRING "Runtime group for hpcc platform")
set(ENV_XML_FILE "environment.xml" CACHE STRING "Name of xml configuration file")
set(ENV_CONF_FILE "environment.conf" CACHE STRING "Name of .conf file")

set(DIR_NAME "HPCCSystems" CACHE STRING "project directory name")
set(LIB_DIR "lib" CACHE STRING "directory for libraries")
set(BIN_DIR "bin" CACHE STRING "directory for executables")
set(SBIN_DIR "sbin" CACHE STRING "directory for scripts")
set(PLUGINS_DIR "plugins" CACHE STRING "directory for plugins")
set(COMP_DIR "componentfiles" CACHE STRING "directory for componentfiles")
set(TEST_DIR "testing" CACHE STRING "directory for test suite")
set(INIT_DIR "etc/init.d" CACHE STRING "directory for installation scripts and helper scripts")
set(SHARE_DIR "share" CACHE STRING "directory for static files that can be shared across network")
set(CLASS_DIR "classes" CACHE STRING "directory for java classes")
set(FILEHOOK_DIR "filehooks" CACHE STRING "directory for filehooks")
set(EXAMPLE_DIR "examples" CACHE STRING "directory for ecl examples")
set(BASH_COMPLETION_DIR "etc/bash_completion.d" CACHE STRING "directory for bash completion scripts")
set(SOURCE_DIR "source" CACHE STRING "direcotyr for configuration source files")
set(CONFIG_DIR "etc/${DIR_NAME}" CACHE STRING "directory for configuration files")

set(RUNTIME_DIR "lib" CACHE STRING "directory for runtime files")
set(LOCK_DIR "lock" CACHE STRING "directory for lock files")
set(PID_DIR "run" CACHE STRING "directory for pid files")
set(LOG_DIR "log" CACHE STRING "directory for log files")
