
if(NOT PREFIX)
    if(WIN32)
        set(prog86key "ProgramFiles(x86)")
        if ("$ENV{${prog86key}}" STREQUAL "")
            set(PREFIX "$ENV{ProgramFiles}")
        else()
            set(PREFIX "$ENV{${prog86key}}")
        endif()
        string(REGEX REPLACE "\\\\" "/" PREFIX ${PREFIX})    
    else(WIN32)
        set(PREFIX "/opt")
    endif(WIN32)    
endif()
if(NOT EXEC_PREFIX)
    set(EXEC_PREFIX "/var")
endif()
if(NOT CONFIG_PREFIX)
    set(CONFIG_PREFIX "/etc")
endif()
if(NOT HOME_DIR)
    set(HOME_DIR "/home")
endif()
if(NOT DIR_NAME)
    set(DIR_NAME "HPCCSystems")
endif()
if(NOT RUNTIME_USER)
    set(RUNTIME_USER "hpcc")
endif()
if(NOT RUNTIME_GROUP)
    set(RUNTIME_GROUP "hpcc")
endif()
if(NOT ENV_XML_FILE)
    set(ENV_XML_FILE "environment.xml")
endif()
if(NOT ENV_CONF_FILE)
    set(ENV_CONF_FILE "environment.conf")
endif()

set(INIT_DIR "${CONFIG_PREFIX}/init.d")

set(SOURCE_DIR "source")
set(LIB_DIR "lib")
set(BIN_DIR "bin")
set(SBIN_DIR "sbin")
set(COMP_DIR "componentfiles")
set(PLUGIN_DIR "plugins")
set(TEST_DIR "testing")
set(FILEHOOK_DIR "filehooks")
set(SHARE_DIR "share")
set(CLASS_DIR "classes")

# relative locations that get appended to $ENV{DESTDIR}CMAKE_INSTALL_PREFIX
# user may override
if(NOT INSTALL_PATH)
    set(INSTALL_PATH "${PREFIX}/${DIR_NAME}")
endif()
if(NOT CONFIG_DIR)
    set(CONFIG_DIR "${CONFIG_PREFIX}/${DIR_NAME}")
endif()
if(NOT CONFIG_SOURCE_DIR)
    set(CONFIG_SOURCE_DIR "${CONFIG_DIR}/${SOURCE_DIR}")
endif()
if(NOT PID_PATH)
    set(PID_PATH "${EXEC_PREFIX}/run/${DIR_NAME}")
endif()
if(NOT LOCK_PATH)
    set(LOCK_PATH "${EXEC_PREFIX}/lock/${DIR_NAME}")
endif()
if(NOT LOG_PATH)
    set(LOG_PATH "${EXEC_PREFIX}/log/${DIR_NAME}")
endif()
if(NOT RUNTIME_PATH)
    set(RUNTIME_PATH "${EXEC_PREFIX}/lib/${DIR_NAME}")
endif()
