version: 1
formatters:
  simpleFileFormat:
    format: '%(asctime)s :: %(name)s :: %(levelname)s :: %(message)s'
  simpleConsoleFormat:
    format: '%(name)s :: %(levelname)s :: %(message)s'
handlers:
  consoleHandler:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simpleConsoleFormat
    stream: ext://sys.stdout
  fileHandler:
    class: logging.FileHandler
    level: DEBUG
    formatter: simpleFileFormat
    filename: pkggen.log
    encoding: 'utf-8'
    mode: 'a'
loggers:
  pkggenLogger:
    level: DEBUG
    propagate: True
    handlers: [consoleHandler, fileHandler]
root:
  handlers: [consoleHandler, fileHandler]
  level: DEBUG
