name: Build Test ECL Watch

on:
  pull_request:
    branches:
      - "master"
      - "candidate-*"
      - "!candidate-7.6.*"
      - "!candidate-7.4.*"
      - "!candidate-7.2.*"
      - "!candidate-7.0.*"
      - "!candidate-6.*"

jobs:
  pre_job:
    runs-on: ubuntu-20.04
    outputs:
      eclwatch: ${{ steps.skip_check.outputs.eclwatch }}
    steps:
      - id: skip_check
        uses: hpcc-systems/github-actions/changed-modules@main
        with:
          github_token: ${{ github.token }}

  build:
    strategy:
      matrix:
        node: ["20", "16", "14"]
      fail-fast: false
    name: "Check eclwatch and npm"
    needs: pre_job
    if: ${{ needs.pre_job.outputs.eclwatch }}
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: ./esp/src/node_modules
          key: npm-deps-${{ hashFiles('./esp/src/package-lock.json') }}
          restore-keys: |
            npm-deps-${{ hashFiles('./esp/src/package-lock.json') }}
      - name: Install Dependencies
        working-directory: ./esp/src
        run: npm ci
      - name: Build
        working-directory: ./esp/src
        run: npm run build
      - name: Test
        working-directory: ./esp/src
        run: npm run test
