name: Build and publish daily image
# This workflow is run every 3 hours during the work week
# Builds current head of master and publishes to docker hub
# using the tag :daily
on:
  schedule:
    -cron: "* */3 * * 1-5"

jobs:
  build:
    name: "Build and publish release container"
    runs-on: ubuntu-latest
    if: github.repository == 'hpcc-systems/HPCC-Platform'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: refs/heads/master
      - name: Build
        uses: ./dockerfiles
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          daily: 1

      - name: Notify on failure
        uses: hpcc-systems/action-send-mail@v2
        if: ${{ failure() }}
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.GMAIL_USER}}
          password: ${{secrets.GMAIL_PW}}
          subject: Github Actions job result
          body: Build job of ${{github.repository}} failed!
          to: ${{secrets.GMAIL_RECIPIENTS}}
          from: Github Actions

