name: Build and publish debug
# This workflow is triggered on new tags of Community Edition 7.8.x or later,
# or any of the weekly tag names starting 'master'
on:
  push:
    tags:
    - 'master*'
    - 'community_*'
    - '!community_7.6.*'
    - '!community_7.4.*'
    - '!community_7.2.*'
    - '!community_7.0.*'
    - '!community_6.*'

jobs:
  build:
    name: "Build and publish debug container"
    runs-on: ubuntu-20.04
    if: github.repository == 'hpcc-systems/HPCC-Platform'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        uses: ./dockerfiles
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          build_type: Debug
          github_actor: ${{ secrets.LNB_ACTOR }}
          github_token: ${{ secrets.LNB_TOKEN }}
          
