name: Build and publish
# This workflow is triggered on new tags of Community Edition 7.8.x or later,
# or any of the weekly tag names starting 'master'
on:
  workflow_dispatch

jobs:
  build:
    name: "Build and publish release container"
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        uses: ./dockerfiles
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          docker_repo: ${{ secrets.DOCKER_REPO }}
          latest: 1   # this should only be set on the current minor branch
          build_user: ${{ secrets.MYBUILD_USER }}
          sign_modules: ON
          signing_secret: ${{ secrets.SIGNING_SECRET }}
          signing_keyid: ${{ secrets.SIGNING_KEYID }}
          signing_passphrase: ${{ secrets.SIGNING_PASSPHRASE }}


