name: Deploy vitepress content to Pages

on:
  push:
    branches:
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Build job
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Generate PDF Assets
        uses: ./.github/actions/build-documentation.yml
        with:
          community-ref: master
          release-package: false
          folder-platform: ${{ github.workspace }}/HPCC-Platform
          folder-build: ${{ github.workspace }}/build
          candidate-base-branch: master
          community-tag: master
          mount-platform: 'source="${{ github.workspace }}/HPCC-Platform",target=/hpcc-dev/HPCC-Platform,type=bind,consistency=cached'
          mount-build: 'source="${{ github.workspace }}/build",target=/hpcc-dev/build,type=bind,consistency=cached'

      - name: Download PDF Assets
        uses: actions/download-artifact@v4
        with:
          name: pdf-documents
      - run: ls -la 
      - run: ls -la ${{ github.workspace }}/pdf-documents
      - run: npm ci
      - run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./devdoc/.vitepress/dist
          force_orphan: true
          # cname: example.com # if wanna deploy to custom domain
        env:
          CI: true
