name: Temp workflow for testing logic

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - run: |
          # Install, configure and start TinyProxy
          sudo apt-get install -y tinyproxy
          echo "Port 8888"    > tinyproxy.conf
          echo "Timeout 600" >> tinyproxy.conf
          tinyproxy -c tinyproxy.conf
          echo "TinyProxy started"
          ps aux | grep tinyproxy
