name: Test Build Validation

on:
  schedule:
    - cron: '0 0 * * 3'
    - cron: '0 0 * * 5'
  workflow_dispatch:
    inputs:
      hpcc_version:
        description: 'HPCC Version'
        required: true
        default: '9.12.14'
      community_tag:
        description: 'Community Tag'
        required: true
        default: 'community_9.12.14-1'
jobs:
  
  test-build-validation-matrix:
    name: "Test published image"
    runs-on: ubuntu-22.04
    if: ${{ github.repository_owner == 'hpcc-systems' && github.event != 'workflow_dispatch' }}
    env:
      WF_YAML_FILE: az-bvt.yml
    strategy:
      matrix:
        hpcc_version: ['9.12', '9.14']
      max-parallel: 1
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
        with:
          ref: master
          fetch-depth: 0
          fetch-tags: true
      - name: "Find Latest Tag"
        id: vars
        run: |
          tag=$(git tag -l | grep ${{matrix.hpcc_version}} | sort -r --version-sort | head -n 1)
          echo "hpcc_version=$(echo $tag | sed 's/community_//' | sed 's/-[0-9]$//')" >> $GITHUB_OUTPUT
          echo "community_tag=$tag" >> $GITHUB_OUTPUT
      - name: "Trigger external azure test code"
        run: |
          data="{\"ref\":\"main\", \"inputs\":{ \"hpccVersion\":\"${{ steps.vars.outputs.hpcc_version }}\",\"hpccSrcBranch\":\"${{ steps.vars.outputs.community_tag }}\" }}"
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GAHT_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/LexisNexis-RBA/hpccplat-build-verification-tests/actions/workflows/$WF_YAML_FILE/dispatches \
          -d "${data}"

  manual-workflow-validation:
    name: "Manual Workflow Validation"
    runs-on: ubuntu-22.04
    if: ${{ github.repository_owner == 'hpcc-systems' && github.event == 'workflow_dispatch' }}
    env:
      WF_YAML_FILE: az-bvt.yml
    steps:
      - name: "Trigger external azure test code"
        run: |
          data="{\"ref\":\"main\", \"inputs\":{ \"hpccVersion\":\"${{ inputs.hpcc_version }}\",\"hpccSrcBranch\":\"${{ inputs.community_tag }}\" }}"
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GAHT_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/LexisNexis-RBA/hpccplat-build-verification-tests/actions/workflows/$WF_YAML_FILE/dispatches \
          -d "${data}"
